# coding: utf-8

"""
    Platform Repository Service

    Platform Repository Service - Sage Bionetworks Platform   # noqa: E501

    The version of the OpenAPI document: develop-SNAPSHOT
    Contact: thomas.yu@sagebionetworks.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import synclient
from synclient.api.discussion_services_api import DiscussionServicesApi  # noqa: E501
from synclient.rest import ApiException


class TestDiscussionServicesApi(unittest.TestCase):
    """DiscussionServicesApi unit test stubs"""

    def setUp(self):
        self.api = synclient.api.discussion_services_api.DiscussionServicesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_threads_for_entity(self):
        """Test case for get_threads_for_entity

        This API is used to get N number of threads that belongs to projects user can view and references the given entity.   # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
