"""
    Platform Repository Service

    Platform Repository Service - Sage Bionetworks Platform   # noqa: E501

    The version of the OpenAPI document: develop-SNAPSHOT
    Contact: thomas.yu@sagebionetworks.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import synclient
from synclient.model.asynchronous_response_body import AsynchronousResponseBody


class TestAsynchronousResponseBody(unittest.TestCase):
    """AsynchronousResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAsynchronousResponseBody(self):
        """Test AsynchronousResponseBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AsynchronousResponseBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
