# coding: utf-8

"""
    Platform Repository Service

    Platform Repository Service - Sage Bionetworks Platform   # noqa: E501

    The version of the OpenAPI document: develop-SNAPSHOT
    Contact: thomas.yu@sagebionetworks.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import synclient
from synclient.api.doi_services_api import DoiServicesApi  # noqa: E501
from synclient.rest import ApiException


class TestDoiServicesApi(unittest.TestCase):
    """DoiServicesApi unit test stubs"""

    def setUp(self):
        self.api = synclient.api.doi_services_api.DoiServicesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_create_or_update_doi_results(self):
        """Test case for get_create_or_update_doi_results

        Get the results of a call to POST /doi/async/start  # noqa: E501
        """
        pass

    def test_get_doi_association(self):
        """Test case for get_doi_association

        Retrieves the DOI for the object.  # noqa: E501
        """
        pass

    def test_get_doi_v2(self):
        """Test case for get_doi_v2

        Retrieves the DOI for the object and its associated DOI metadata.  # noqa: E501
        """
        pass

    def test_locate(self):
        """Test case for locate

        Retrieves the Synapse web portal URL to the object entered.  # noqa: E501
        """
        pass

    def test_start_create_or_update_doi(self):
        """Test case for start_create_or_update_doi

        Asynchronously creates or updates a DOI in Synapse, with input metadata.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
