# coding: utf-8

"""
    Platform Repository Service

    Platform Repository Service - Sage Bionetworks Platform   # noqa: E501

    The version of the OpenAPI document: develop-SNAPSHOT
    Contact: thomas.yu@sagebionetworks.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import synclient
from synclient.models.submission_status_form import SubmissionStatusForm  # noqa: E501
from synclient.rest import ApiException

class TestSubmissionStatusForm(unittest.TestCase):
    """SubmissionStatusForm unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SubmissionStatusForm
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = synclient.models.submission_status_form.SubmissionStatusForm()  # noqa: E501
        if include_optional :
            return SubmissionStatusForm(
                rejection_message = '0', 
                reviewed_by = '0', 
                reviewed_on = '0', 
                state = 'WAITING_FOR_SUBMISSION', 
                submitted_on = '0'
            )
        else :
            return SubmissionStatusForm(
        )

    def testSubmissionStatusForm(self):
        """Test SubmissionStatusForm"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
