# coding: utf-8

"""
    Platform Repository Service

    Platform Repository Service - Sage Bionetworks Platform   # noqa: E501

    The version of the OpenAPI document: develop-SNAPSHOT
    Contact: thomas.yu@sagebionetworks.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import synclient
from synclient.models.member_submission_eligibility import MemberSubmissionEligibility  # noqa: E501
from synclient.rest import ApiException

class TestMemberSubmissionEligibility(unittest.TestCase):
    """MemberSubmissionEligibility unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test MemberSubmissionEligibility
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = synclient.models.member_submission_eligibility.MemberSubmissionEligibility()  # noqa: E501
        if include_optional :
            return MemberSubmissionEligibility(
                has_conflicting_submission = True, 
                is_eligible = True, 
                is_quota_filled = True, 
                is_registered = True, 
                principal_id = 1.337
            )
        else :
            return MemberSubmissionEligibility(
        )

    def testMemberSubmissionEligibility(self):
        """Test MemberSubmissionEligibility"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
