"""
    Platform Repository Service

    Platform Repository Service - Sage Bionetworks Platform   # noqa: E501

    The version of the OpenAPI document: develop-SNAPSHOT
    Contact: thomas.yu@sagebionetworks.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import synclient
from synclient.model.submission_order import SubmissionOrder
from synclient.model.submission_state import SubmissionState
globals()['SubmissionOrder'] = SubmissionOrder
globals()['SubmissionState'] = SubmissionState
from synclient.model.submission_page_request import SubmissionPageRequest


class TestSubmissionPageRequest(unittest.TestCase):
    """SubmissionPageRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubmissionPageRequest(self):
        """Test SubmissionPageRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SubmissionPageRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
