# coding: utf-8

"""
    Platform Repository Service

    Platform Repository Service - Sage Bionetworks Platform   # noqa: E501

    The version of the OpenAPI document: develop-SNAPSHOT
    Contact: thomas.yu@sagebionetworks.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import synclient
from synclient.models.file_handle import FileHandle  # noqa: E501
from synclient.rest import ApiException

class TestFileHandle(unittest.TestCase):
    """FileHandle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test FileHandle
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = synclient.models.file_handle.FileHandle()  # noqa: E501
        if include_optional :
            return FileHandle(
                concrete_type = '0', 
                content_md5 = '0', 
                content_size = 56, 
                content_type = '0', 
                created_by = '0', 
                created_on = '0', 
                etag = '0', 
                file_name = '0', 
                id = '0', 
                storage_location_id = 56
            )
        else :
            return FileHandle(
        )

    def testFileHandle(self):
        """Test FileHandle"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
