# coding: utf-8

"""
    Platform Repository Service

    Platform Repository Service - Sage Bionetworks Platform   # noqa: E501

    The version of the OpenAPI document: develop-SNAPSHOT
    Contact: thomas.yu@sagebionetworks.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import synclient
from synclient.models.column_model import ColumnModel  # noqa: E501
from synclient.rest import ApiException

class TestColumnModel(unittest.TestCase):
    """ColumnModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ColumnModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = synclient.models.column_model.ColumnModel()  # noqa: E501
        if include_optional :
            return ColumnModel(
                column_type = 'STRING', 
                default_value = '0', 
                enum_values = [
                    '0'
                    ], 
                facet_type = 'enumeration', 
                id = '0', 
                maximum_list_length = 1, 
                maximum_size = 1.337, 
                name = '0'
            )
        else :
            return ColumnModel(
        )

    def testColumnModel(self):
        """Test ColumnModel"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
