# coding: utf-8

"""
    Platform Repository Service

    Platform Repository Service - Sage Bionetworks Platform   # noqa: E501

    The version of the OpenAPI document: develop-SNAPSHOT
    Contact: thomas.yu@sagebionetworks.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import synclient
from synclient.api.trash_services_api import TrashServicesApi  # noqa: E501
from synclient.rest import ApiException


class TestTrashServicesApi(unittest.TestCase):
    """TrashServicesApi unit test stubs"""

    def setUp(self):
        self.api = synclient.api.trash_services_api.TrashServicesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_flag_for_purge(self):
        """Test case for flag_for_purge

        Flags the specified entity for priority purge.  # noqa: E501
        """
        pass

    def test_move_to_trash(self):
        """Test case for move_to_trash

        Moves an entity and its descendants to the trash can.  # noqa: E501
        """
        pass

    def test_restore_from_trash(self):
        """Test case for restore_from_trash

        Moves an entity and its descendants out of the trash can back to its original parent.   # noqa: E501
        """
        pass

    def test_restore_from_trash_to_parent(self):
        """Test case for restore_from_trash_to_parent

        Moves an entity and its descendants out of the trash can to a new parent.  # noqa: E501
        """
        pass

    def test_view_trash(self):
        """Test case for view_trash

        Retrieves the paginated list of trash entities deleted by the current user.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
