# coding: utf-8

"""
    Platform Repository Service

    Platform Repository Service - Sage Bionetworks Platform   # noqa: E501

    The version of the OpenAPI document: develop-SNAPSHOT
    Contact: thomas.yu@sagebionetworks.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import synclient
from synclient.models.user_bundle import UserBundle  # noqa: E501
from synclient.rest import ApiException

class TestUserBundle(unittest.TestCase):
    """UserBundle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test UserBundle
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = synclient.models.user_bundle.UserBundle()  # noqa: E501
        if include_optional :
            return UserBundle(
                orcid = '0', 
                is_act_member = True, 
                is_certified = True, 
                is_verified = True, 
                user_id = '0', 
                user_profile = {"RStudioUrl":"...","company":"...","createdOn":"...","displayName":"...","email":"...","emails":["...","..."],"etag":"...","firstName":"...","industry":"...","lastName":"...","location":"...","notificationSettings":{"markEmailedMessagesAsRead":true,"sendEmailNotifications":true},"openIds":["...","..."],"ownerId":"...","position":"...","preferences":[{"concreteType":"...","name":"..."},{"concreteType":"...","name":"..."}],"profilePicureFileHandleId":"...","summary":"...","teamName":"...","url":"...","userName":"..."}, 
                verification_submission = {"attachments":[{"fileName":"...","id":"..."},{"fileName":"...","id":"..."}],"company":"...","createdBy":"...","createdOn":"...","emails":["...","..."],"firstName":"...","id":"...","lastName":"...","location":"...","notificationEmail":"...","orcid":"...","stateHistory":[{"createdBy":"...","createdOn":"...","notes":"...","reason":"...","state":"SUSPENDED"},{"createdBy":"...","createdOn":"...","notes":"...","reason":"...","state":"SUSPENDED"}]}
            )
        else :
            return UserBundle(
        )

    def testUserBundle(self):
        """Test UserBundle"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
