# coding: utf-8

"""
    Platform Repository Service

    Platform Repository Service - Sage Bionetworks Platform   # noqa: E501

    The version of the OpenAPI document: develop-SNAPSHOT
    Contact: thomas.yu@sagebionetworks.org
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from synclient.configuration import Configuration


class FormData(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'created_by': 'str',
        'created_on': 'str',
        'data_file_handle_id': 'str',
        'etag': 'str',
        'form_data_id': 'str',
        'group_id': 'str',
        'modified_on': 'str',
        'name': 'str',
        'submission_status': 'SubmissionStatusForm'
    }

    attribute_map = {
        'created_by': 'createdBy',
        'created_on': 'createdOn',
        'data_file_handle_id': 'dataFileHandleId',
        'etag': 'etag',
        'form_data_id': 'formDataId',
        'group_id': 'groupId',
        'modified_on': 'modifiedOn',
        'name': 'name',
        'submission_status': 'submissionStatus'
    }

    def __init__(self, created_by=None, created_on=None, data_file_handle_id=None, etag=None, form_data_id=None, group_id=None, modified_on=None, name=None, submission_status=None, local_vars_configuration=None):  # noqa: E501
        """FormData - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._created_by = None
        self._created_on = None
        self._data_file_handle_id = None
        self._etag = None
        self._form_data_id = None
        self._group_id = None
        self._modified_on = None
        self._name = None
        self._submission_status = None
        self.discriminator = None

        if created_by is not None:
            self.created_by = created_by
        if created_on is not None:
            self.created_on = created_on
        if data_file_handle_id is not None:
            self.data_file_handle_id = data_file_handle_id
        if etag is not None:
            self.etag = etag
        if form_data_id is not None:
            self.form_data_id = form_data_id
        if group_id is not None:
            self.group_id = group_id
        if modified_on is not None:
            self.modified_on = modified_on
        if name is not None:
            self.name = name
        if submission_status is not None:
            self.submission_status = submission_status

    @property
    def created_by(self):
        """Gets the created_by of this FormData.  # noqa: E501

        Id of the user that created this object  # noqa: E501

        :return: The created_by of this FormData.  # noqa: E501
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this FormData.

        Id of the user that created this object  # noqa: E501

        :param created_by: The created_by of this FormData.  # noqa: E501
        :type: str
        """

        self._created_by = created_by

    @property
    def created_on(self):
        """Gets the created_on of this FormData.  # noqa: E501

        The date this object was originally created.  # noqa: E501

        :return: The created_on of this FormData.  # noqa: E501
        :rtype: str
        """
        return self._created_on

    @created_on.setter
    def created_on(self, created_on):
        """Sets the created_on of this FormData.

        The date this object was originally created.  # noqa: E501

        :param created_on: The created_on of this FormData.  # noqa: E501
        :type: str
        """

        self._created_on = created_on

    @property
    def data_file_handle_id(self):
        """Gets the data_file_handle_id of this FormData.  # noqa: E501

        The identifier of the data FileHandle for this object.  # noqa: E501

        :return: The data_file_handle_id of this FormData.  # noqa: E501
        :rtype: str
        """
        return self._data_file_handle_id

    @data_file_handle_id.setter
    def data_file_handle_id(self, data_file_handle_id):
        """Sets the data_file_handle_id of this FormData.

        The identifier of the data FileHandle for this object.  # noqa: E501

        :param data_file_handle_id: The data_file_handle_id of this FormData.  # noqa: E501
        :type: str
        """

        self._data_file_handle_id = data_file_handle_id

    @property
    def etag(self):
        """Gets the etag of this FormData.  # noqa: E501

        Will change whenever there is a change to the this data or its status.  # noqa: E501

        :return: The etag of this FormData.  # noqa: E501
        :rtype: str
        """
        return self._etag

    @etag.setter
    def etag(self, etag):
        """Sets the etag of this FormData.

        Will change whenever there is a change to the this data or its status.  # noqa: E501

        :param etag: The etag of this FormData.  # noqa: E501
        :type: str
        """

        self._etag = etag

    @property
    def form_data_id(self):
        """Gets the form_data_id of this FormData.  # noqa: E501

        The system issued identifier that uniquely identifies this object.  # noqa: E501

        :return: The form_data_id of this FormData.  # noqa: E501
        :rtype: str
        """
        return self._form_data_id

    @form_data_id.setter
    def form_data_id(self, form_data_id):
        """Sets the form_data_id of this FormData.

        The system issued identifier that uniquely identifies this object.  # noqa: E501

        :param form_data_id: The form_data_id of this FormData.  # noqa: E501
        :type: str
        """

        self._form_data_id = form_data_id

    @property
    def group_id(self):
        """Gets the group_id of this FormData.  # noqa: E501

        The identifier of the group that manages this data. Required.  # noqa: E501

        :return: The group_id of this FormData.  # noqa: E501
        :rtype: str
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id):
        """Sets the group_id of this FormData.

        The identifier of the group that manages this data. Required.  # noqa: E501

        :param group_id: The group_id of this FormData.  # noqa: E501
        :type: str
        """

        self._group_id = group_id

    @property
    def modified_on(self):
        """Gets the modified_on of this FormData.  # noqa: E501

        The date this object was last modified.  # noqa: E501

        :return: The modified_on of this FormData.  # noqa: E501
        :rtype: str
        """
        return self._modified_on

    @modified_on.setter
    def modified_on(self, modified_on):
        """Sets the modified_on of this FormData.

        The date this object was last modified.  # noqa: E501

        :param modified_on: The modified_on of this FormData.  # noqa: E501
        :type: str
        """

        self._modified_on = modified_on

    @property
    def name(self):
        """Gets the name of this FormData.  # noqa: E501

        User provided name for this submission. Required.  # noqa: E501

        :return: The name of this FormData.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this FormData.

        User provided name for this submission. Required.  # noqa: E501

        :param name: The name of this FormData.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def submission_status(self):
        """Gets the submission_status of this FormData.  # noqa: E501


        :return: The submission_status of this FormData.  # noqa: E501
        :rtype: SubmissionStatusForm
        """
        return self._submission_status

    @submission_status.setter
    def submission_status(self, submission_status):
        """Sets the submission_status of this FormData.


        :param submission_status: The submission_status of this FormData.  # noqa: E501
        :type: SubmissionStatusForm
        """

        self._submission_status = submission_status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FormData):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, FormData):
            return True

        return self.to_dict() != other.to_dict()
