# coding: utf-8

"""
    Platform Repository Service

    Platform Repository Service - Sage Bionetworks Platform   # noqa: E501

    The version of the OpenAPI document: develop-SNAPSHOT
    Contact: thomas.yu@sagebionetworks.org
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from synclient.configuration import Configuration


class StringAnnotation(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'is_private': 'bool',
        'key': 'str',
        'value': 'str'
    }

    attribute_map = {
        'is_private': 'isPrivate',
        'key': 'key',
        'value': 'value'
    }

    def __init__(self, is_private=None, key=None, value=None, local_vars_configuration=None):  # noqa: E501
        """StringAnnotation - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._is_private = None
        self._key = None
        self._value = None
        self.discriminator = None

        if is_private is not None:
            self.is_private = is_private
        if key is not None:
            self.key = key
        if value is not None:
            self.value = value

    @property
    def is_private(self):
        """Gets the is_private of this StringAnnotation.  # noqa: E501

        Flag denoting whether this Annotation should be private.  # noqa: E501

        :return: The is_private of this StringAnnotation.  # noqa: E501
        :rtype: bool
        """
        return self._is_private

    @is_private.setter
    def is_private(self, is_private):
        """Sets the is_private of this StringAnnotation.

        Flag denoting whether this Annotation should be private.  # noqa: E501

        :param is_private: The is_private of this StringAnnotation.  # noqa: E501
        :type: bool
        """

        self._is_private = is_private

    @property
    def key(self):
        """Gets the key of this StringAnnotation.  # noqa: E501

        The key of this Annotation  # noqa: E501

        :return: The key of this StringAnnotation.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this StringAnnotation.

        The key of this Annotation  # noqa: E501

        :param key: The key of this StringAnnotation.  # noqa: E501
        :type: str
        """

        self._key = key

    @property
    def value(self):
        """Gets the value of this StringAnnotation.  # noqa: E501

        The value of this Annotation  # noqa: E501

        :return: The value of this StringAnnotation.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this StringAnnotation.

        The value of this Annotation  # noqa: E501

        :param value: The value of this StringAnnotation.  # noqa: E501
        :type: str
        """

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StringAnnotation):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, StringAnnotation):
            return True

        return self.to_dict() != other.to_dict()
