# coding: utf-8

"""
    Platform Repository Service

    Platform Repository Service - Sage Bionetworks Platform   # noqa: E501

    The version of the OpenAPI document: develop-SNAPSHOT
    Contact: thomas.yu@sagebionetworks.org
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from synclient.configuration import Configuration


class TeamMember(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'is_admin': 'bool',
        'member': 'UserGroupHeader',
        'team_id': 'str'
    }

    attribute_map = {
        'is_admin': 'isAdmin',
        'member': 'member',
        'team_id': 'teamId'
    }

    def __init__(self, is_admin=None, member=None, team_id=None, local_vars_configuration=None):  # noqa: E501
        """TeamMember - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._is_admin = None
        self._member = None
        self._team_id = None
        self.discriminator = None

        if is_admin is not None:
            self.is_admin = is_admin
        if member is not None:
            self.member = member
        if team_id is not None:
            self.team_id = team_id

    @property
    def is_admin(self):
        """Gets the is_admin of this TeamMember.  # noqa: E501

        True if the user is an administrator in the Team.  # noqa: E501

        :return: The is_admin of this TeamMember.  # noqa: E501
        :rtype: bool
        """
        return self._is_admin

    @is_admin.setter
    def is_admin(self, is_admin):
        """Sets the is_admin of this TeamMember.

        True if the user is an administrator in the Team.  # noqa: E501

        :param is_admin: The is_admin of this TeamMember.  # noqa: E501
        :type: bool
        """

        self._is_admin = is_admin

    @property
    def member(self):
        """Gets the member of this TeamMember.  # noqa: E501


        :return: The member of this TeamMember.  # noqa: E501
        :rtype: UserGroupHeader
        """
        return self._member

    @member.setter
    def member(self, member):
        """Sets the member of this TeamMember.


        :param member: The member of this TeamMember.  # noqa: E501
        :type: UserGroupHeader
        """

        self._member = member

    @property
    def team_id(self):
        """Gets the team_id of this TeamMember.  # noqa: E501

        The id of the Team.  # noqa: E501

        :return: The team_id of this TeamMember.  # noqa: E501
        :rtype: str
        """
        return self._team_id

    @team_id.setter
    def team_id(self, team_id):
        """Sets the team_id of this TeamMember.

        The id of the Team.  # noqa: E501

        :param team_id: The team_id of this TeamMember.  # noqa: E501
        :type: str
        """

        self._team_id = team_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TeamMember):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TeamMember):
            return True

        return self.to_dict() != other.to_dict()
