# coding: utf-8

"""
    Platform Repository Service

    Platform Repository Service - Sage Bionetworks Platform   # noqa: E501

    The version of the OpenAPI document: develop-SNAPSHOT
    Contact: thomas.yu@sagebionetworks.org
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from synclient.configuration import Configuration


class WikiPageKey(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'owner_object_id': 'str',
        'owner_object_type': 'ObjectType',
        'wiki_page_id': 'str'
    }

    attribute_map = {
        'owner_object_id': 'ownerObjectId',
        'owner_object_type': 'ownerObjectType',
        'wiki_page_id': 'wikiPageId'
    }

    def __init__(self, owner_object_id=None, owner_object_type=None, wiki_page_id=None, local_vars_configuration=None):  # noqa: E501
        """WikiPageKey - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._owner_object_id = None
        self._owner_object_type = None
        self._wiki_page_id = None
        self.discriminator = None

        if owner_object_id is not None:
            self.owner_object_id = owner_object_id
        if owner_object_type is not None:
            self.owner_object_type = owner_object_type
        if wiki_page_id is not None:
            self.wiki_page_id = wiki_page_id

    @property
    def owner_object_id(self):
        """Gets the owner_object_id of this WikiPageKey.  # noqa: E501

        The owner of this page.  # noqa: E501

        :return: The owner_object_id of this WikiPageKey.  # noqa: E501
        :rtype: str
        """
        return self._owner_object_id

    @owner_object_id.setter
    def owner_object_id(self, owner_object_id):
        """Sets the owner_object_id of this WikiPageKey.

        The owner of this page.  # noqa: E501

        :param owner_object_id: The owner_object_id of this WikiPageKey.  # noqa: E501
        :type: str
        """

        self._owner_object_id = owner_object_id

    @property
    def owner_object_type(self):
        """Gets the owner_object_type of this WikiPageKey.  # noqa: E501


        :return: The owner_object_type of this WikiPageKey.  # noqa: E501
        :rtype: ObjectType
        """
        return self._owner_object_type

    @owner_object_type.setter
    def owner_object_type(self, owner_object_type):
        """Sets the owner_object_type of this WikiPageKey.


        :param owner_object_type: The owner_object_type of this WikiPageKey.  # noqa: E501
        :type: ObjectType
        """

        self._owner_object_type = owner_object_type

    @property
    def wiki_page_id(self):
        """Gets the wiki_page_id of this WikiPageKey.  # noqa: E501

        The ID of the wiki page.  # noqa: E501

        :return: The wiki_page_id of this WikiPageKey.  # noqa: E501
        :rtype: str
        """
        return self._wiki_page_id

    @wiki_page_id.setter
    def wiki_page_id(self, wiki_page_id):
        """Sets the wiki_page_id of this WikiPageKey.

        The ID of the wiki page.  # noqa: E501

        :param wiki_page_id: The wiki_page_id of this WikiPageKey.  # noqa: E501
        :type: str
        """

        self._wiki_page_id = wiki_page_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WikiPageKey):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, WikiPageKey):
            return True

        return self.to_dict() != other.to_dict()
